[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.9"
chumsky = "0.9.3"

[dev-dependencies]
indoc = "2.0.4"
